case_number: 1
dt: 1
initial_time: 0
sim_time: 500
animation: True
origin_lon: 122.28
origin_lat: 29.87

LOA_own: 30
BOL_own: 16

num_obstacles: 1
LOA_ob: 10
BOL_ob: 5





vessel_data: data/path_data_1.csv
output_dir: results/